// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ci_func_cpp
NumericMatrix ci_func_cpp(NumericMatrix x, int df, Nullable<double> min_D, Nullable<CharacterVector> names);
RcppExport SEXP _multiScaleR_ci_func_cpp(SEXP xSEXP, SEXP dfSEXP, SEXP min_DSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type min_D(min_DSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type names(namesSEXP);
    rcpp_result_gen = Rcpp::wrap(ci_func_cpp(x, df, min_D, names));
    return rcpp_result_gen;
END_RCPP
}
// landscape_composition_metric_cpp
NumericVector landscape_composition_metric_cpp(NumericVector d, NumericMatrix values, double radius, std::string metric, Nullable<NumericVector> weights_, double base, Nullable<double> resolution_, Nullable<double> classes_max_, Nullable<double> focal_class_);
RcppExport SEXP _multiScaleR_landscape_composition_metric_cpp(SEXP dSEXP, SEXP valuesSEXP, SEXP radiusSEXP, SEXP metricSEXP, SEXP weights_SEXP, SEXP baseSEXP, SEXP resolution_SEXP, SEXP classes_max_SEXP, SEXP focal_class_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type weights_(weights_SEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type resolution_(resolution_SEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type classes_max_(classes_max_SEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type focal_class_(focal_class_SEXP);
    rcpp_result_gen = Rcpp::wrap(landscape_composition_metric_cpp(d, values, radius, metric, weights_, base, resolution_, classes_max_, focal_class_));
    return rcpp_result_gen;
END_RCPP
}
// landscape_edge_metric_cpp
NumericVector landscape_edge_metric_cpp(NumericVector d, NumericMatrix values, NumericVector cells, double radius, double resolution, int n_cols, std::string metric);
RcppExport SEXP _multiScaleR_landscape_edge_metric_cpp(SEXP dSEXP, SEXP valuesSEXP, SEXP cellsSEXP, SEXP radiusSEXP, SEXP resolutionSEXP, SEXP n_colsSEXP, SEXP metricSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cells(cellsSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< double >::type resolution(resolutionSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    rcpp_result_gen = Rcpp::wrap(landscape_edge_metric_cpp(d, values, cells, radius, resolution, n_cols, metric));
    return rcpp_result_gen;
END_RCPP
}
// landscape_adjacency_metric_cpp
NumericVector landscape_adjacency_metric_cpp(NumericVector d, NumericMatrix values, NumericVector cells, double radius, int n_cols, std::string metric, double base, Nullable<double> focal_class_);
RcppExport SEXP _multiScaleR_landscape_adjacency_metric_cpp(SEXP dSEXP, SEXP valuesSEXP, SEXP cellsSEXP, SEXP radiusSEXP, SEXP n_colsSEXP, SEXP metricSEXP, SEXP baseSEXP, SEXP focal_class_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cells(cellsSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< int >::type n_cols(n_colsSEXP);
    Rcpp::traits::input_parameter< std::string >::type metric(metricSEXP);
    Rcpp::traits::input_parameter< double >::type base(baseSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type focal_class_(focal_class_SEXP);
    rcpp_result_gen = Rcpp::wrap(landscape_adjacency_metric_cpp(d, values, cells, radius, n_cols, metric, base, focal_class_));
    return rcpp_result_gen;
END_RCPP
}
// scale_type_cpp
NumericVector scale_type_cpp(NumericVector d, std::string kernel, Nullable<NumericVector> sigma_, Nullable<NumericVector> shape_, Nullable<NumericMatrix> r_stack_df, Nullable<int> output);
RcppExport SEXP _multiScaleR_scale_type_cpp(SEXP dSEXP, SEXP kernelSEXP, SEXP sigma_SEXP, SEXP shape_SEXP, SEXP r_stack_dfSEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type sigma_(sigma_SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type shape_(shape_SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type r_stack_df(r_stack_dfSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type output(outputSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_type_cpp(d, kernel, sigma_, shape_, r_stack_df, output));
    return rcpp_result_gen;
END_RCPP
}
// scale_type_sparse
NumericVector scale_type_sparse(NumericVector d, std::string kernel, Nullable<NumericVector> sigma_, Nullable<NumericVector> shape_, Nullable<RObject> r_stack_df, Nullable<std::string> output);
RcppExport SEXP _multiScaleR_scale_type_sparse(SEXP dSEXP, SEXP kernelSEXP, SEXP sigma_SEXP, SEXP shape_SEXP, SEXP r_stack_dfSEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type sigma_(sigma_SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type shape_(shape_SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type r_stack_df(r_stack_dfSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type output(outputSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_type_sparse(d, kernel, sigma_, shape_, r_stack_df, output));
    return rcpp_result_gen;
END_RCPP
}
// surface_sa_focal_cpp
NumericMatrix surface_sa_focal_cpp(NumericMatrix values, NumericMatrix kernel);
RcppExport SEXP _multiScaleR_surface_sa_focal_cpp(SEXP valuesSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(surface_sa_focal_cpp(values, kernel));
    return rcpp_result_gen;
END_RCPP
}
