// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ci_func_cpp
NumericMatrix ci_func_cpp(NumericMatrix x, int df, Nullable<double> min_D, Nullable<CharacterVector> names);
RcppExport SEXP _multiScaleR_ci_func_cpp(SEXP xSEXP, SEXP dfSEXP, SEXP min_DSEXP, SEXP namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type min_D(min_DSEXP);
    Rcpp::traits::input_parameter< Nullable<CharacterVector> >::type names(namesSEXP);
    rcpp_result_gen = Rcpp::wrap(ci_func_cpp(x, df, min_D, names));
    return rcpp_result_gen;
END_RCPP
}
// scale_type_cpp
NumericVector scale_type_cpp(NumericVector d, std::string kernel, Nullable<NumericVector> sigma_, Nullable<NumericVector> shape_, Nullable<NumericMatrix> r_stack_df, Nullable<int> output);
RcppExport SEXP _multiScaleR_scale_type_cpp(SEXP dSEXP, SEXP kernelSEXP, SEXP sigma_SEXP, SEXP shape_SEXP, SEXP r_stack_dfSEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type sigma_(sigma_SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type shape_(shape_SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericMatrix> >::type r_stack_df(r_stack_dfSEXP);
    Rcpp::traits::input_parameter< Nullable<int> >::type output(outputSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_type_cpp(d, kernel, sigma_, shape_, r_stack_df, output));
    return rcpp_result_gen;
END_RCPP
}
// scale_type_sparse
NumericVector scale_type_sparse(NumericVector d, std::string kernel, Nullable<NumericVector> sigma_, Nullable<NumericVector> shape_, Nullable<RObject> r_stack_df, Nullable<std::string> output);
RcppExport SEXP _multiScaleR_scale_type_sparse(SEXP dSEXP, SEXP kernelSEXP, SEXP sigma_SEXP, SEXP shape_SEXP, SEXP r_stack_dfSEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< std::string >::type kernel(kernelSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type sigma_(sigma_SEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type shape_(shape_SEXP);
    Rcpp::traits::input_parameter< Nullable<RObject> >::type r_stack_df(r_stack_dfSEXP);
    Rcpp::traits::input_parameter< Nullable<std::string> >::type output(outputSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_type_sparse(d, kernel, sigma_, shape_, r_stack_df, output));
    return rcpp_result_gen;
END_RCPP
}
