# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ci_func_cpp <- function(x, df, min_D = NULL, names = NULL) {
    .Call(`_multiScaleR_ci_func_cpp`, x, df, min_D, names)
}

scale_type_cpp <- function(d, kernel = "gaussian", sigma_ = NULL, shape_ = NULL, r_stack_df = NULL, output = NULL) {
    .Call(`_multiScaleR_scale_type_cpp`, d, kernel, sigma_, shape_, r_stack_df, output)
}

