# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ci_func_cpp <- function(x, df, min_D = NULL, names = NULL) {
    .Call(`_multiScaleR_ci_func_cpp`, x, df, min_D, names)
}

landscape_composition_metric_cpp <- function(d, values, radius, metric, weights_, base, resolution_, classes_max_) {
    .Call(`_multiScaleR_landscape_composition_metric_cpp`, d, values, radius, metric, weights_, base, resolution_, classes_max_)
}

landscape_edge_metric_cpp <- function(d, values, cells, radius, resolution, n_cols, metric) {
    .Call(`_multiScaleR_landscape_edge_metric_cpp`, d, values, cells, radius, resolution, n_cols, metric)
}

landscape_adjacency_metric_cpp <- function(d, values, cells, radius, n_cols, metric) {
    .Call(`_multiScaleR_landscape_adjacency_metric_cpp`, d, values, cells, radius, n_cols, metric)
}

scale_type_cpp <- function(d, kernel = "gaussian", sigma_ = NULL, shape_ = NULL, r_stack_df = NULL, output = NULL) {
    .Call(`_multiScaleR_scale_type_cpp`, d, kernel, sigma_, shape_, r_stack_df, output)
}

scale_type_sparse <- function(d, kernel = "gaussian", sigma_ = NULL, shape_ = NULL, r_stack_df = NULL, output = NULL) {
    .Call(`_multiScaleR_scale_type_sparse`, d, kernel, sigma_, shape_, r_stack_df, output)
}

